apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.26.5
          command: ["/usr/local/bin/envoy"]
          args: ["-c", "/etc/envoy/envoy.yaml",  "--log-level", "debug", "--service-node", "node1", "--service-cluster", "cluster1"]
          ports:
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config-volume
          configMap:
            name: envoy-config