apiVersion: v1
kind: Service
metadata:
  name: grpc-streaming
  namespace: test
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: HTTP2
    name: http-server
    port: 80
    protocol: TCP
    targetPort: primary
  selector:
    app: grpc-streaming
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
