
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-streaming
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-streaming
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      annotations:
        barito_enabled: "false"
      creationTimestamp: null
      labels:
        app: grpc-streaming
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - grpc-streaming
              namespaces:
              - test
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      automountServiceAccountToken: true
      containers:
      - image: pokekrishna/grpc-streaming:v1.2.0
        command: [ "go", "run", ".", "--as_server"] # Added command here
        imagePullPolicy: Always
        name: grpc-streaming
        ports:
        - containerPort: 8080
          name: primary
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 300m
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
